plugins {
    id 'java-library'
    id 'eclipse'
}

jar {
    manifest {
        attributes 'Implementation-Title': 'Signature Standard PAdES'
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

task releases(type: Copy) {
    from jar.outputs
    into rootDir.toString() + "/releases/" + version
}

releases.dependsOn jar
releases.dependsOn sourcesJar

dependencies {
    implementation project(':pdf-as-lib')
    implementation project(':pdf-as-common')
    implementation group: 'org.apache.commons', name: 'commons-collections4', version:  commonsCollectionsVersion
    implementation group: 'org.slf4j', name: 'slf4j-api', version: slf4jVersion
}

test {
    systemProperties 'property': 'value'
}
