plugins {
	id 'java-library'
	id 'eclipse'
	id 'distribution'
}

jar {
	manifest {
		attributes 'Implementation-Title': 'PDF-AS-4 Web Extension Library', 'JARMANIFEST': 'PDF-AS-LIB'
	}
}

repositories {
	mavenLocal()
	mavenCentral()
}

dependencies {
	implementation project (':pdf-as-web')
	implementation project (':pdf-as-web-status')
	implementation project (':pdf-as-web-statistic-api')
	api "org.hibernate:hibernate-core:6.6.4.Final"
	implementation group: 'ch.qos.logback', name: 'logback-classic', version: logbackVersion
	implementation group: 'org.slf4j', name: 'slf4j-api', version: slf4jVersion
}

task releases(type: Copy) {
	from jar.outputs
	from distZip.outputs
	from distTar.outputs
	into rootDir.toString() + "/releases/" + version
}

releases.dependsOn jar
releases.dependsOn sourcesJar
releases.dependsOn distZip
releases.dependsOn distTar
