apply plugin: 'java-library'
apply plugin: 'eclipse'

jar {
    manifest {
        attributes 'Implementation-Title': 'PDF-AS-4 Commons'
    }
}

repositories {
    mavenCentral()
}

task releases(type: Copy) {
	from jar.outputs
	into rootDir.toString() + "/releases/" + version
}

releases.dependsOn jar
releases.dependsOn sourcesJar

dependencies {
	api group: 'org.slf4j', name: 'slf4j-api', version: slf4jVersion
    api group: 'org.apache.commons', name: 'commons-collections4', version: commonsCollectionsVersion
	api group: 'commons-io', name: 'commons-io', version: commonsIoVersion
	api group: 'ognl', name: 'ognl', version: ognlVersion
    api group: 'jakarta.xml.bind', name: 'jakarta.xml.bind-api', version: jaxbApiVersion
	api group: 'commons-codec', name: 'commons-codec', version: commonsCodecVersion
    api group: 'org.glassfish.jaxb', name: 'jaxb-runtime', version: jaxbRuntimeVersion
    api group: 'jakarta.jws', name: 'jakarta.jws-api', version: jakartaJwsVersion
    testImplementation group: 'junit', name: 'junit', version: junitVersion
}

test {
    systemProperties 'property': 'value'
}

