
###################################################################################################
# PROFIL: Standardsignatur Deutsch 

# Kurzbeschreibung
sig_obj.SIGNATURBLOCK_DE_FORCE.description=Standardsignatur Deutsch
sig_obj.SIGNATURBLOCK_DE_FORCE.parent=BASE_NORMAL
sig_obj.SIGNATURBLOCK_DE_FORCE.SIGNED_NEWPAGE_FORCE=true
sig_obj.types.SIGNATURBLOCK_DE_FORCE=on
