apply plugin: 'java-library'
apply plugin: 'eclipse'
apply plugin: 'java-library-distribution'

jar {
	manifest {
		attributes 'Implementation-Title': 'PDF-AS-5 MOA Library', 'JARMANIFEST': 'PDF-AS-LIB'
	}
}

buildscript {
	repositories {
		mavenLocal()
		mavenCentral()
	}
	dependencies { classpath("commons-io:commons-io:"+commonsIoVersion) }
}

sourceSets {
	main {
		java {
			srcDirs = [ 'src/main/java', 'src/generated/java' ]
		}
	}
}

configurations { 
	ws 
	
	pdfDoclet { extendsFrom compileClasspath }
}

project.ext {
	wsdlDir = file("src/main/resources/wsdl")
	generatedWsdlDir = file("src/generated/java")
	wsdlsToGenerate = [
			   ['-xjc', 
				    "$wsdlDir/MOA-SPSS-2.0.0.wsdl"],
	 ]
}

repositories {
	mavenLocal()
	mavenCentral()
}

dependencies {
	implementation project (':pdf-as-lib')
	implementation group: 'org.slf4j', name: 'slf4j-api', version: slf4jVersion
	
	// Jakarta EE XML Binding (JAXB) - migrated from javax.xml.bind
	implementation group: 'jakarta.xml.bind', name: 'jakarta.xml.bind-api', version: jaxbApiVersion
	implementation group: 'org.glassfish.jaxb', name: 'jaxb-runtime', version: jaxbRuntimeVersion
	
	// Jakarta EE XML Web Services (JAX-WS) - migrated from javax.xml.ws
	api group: 'jakarta.xml.ws', name: 'jakarta.xml.ws-api', version: jakartaXmlWsVersion
	api group: 'jakarta.jws', name: 'jakarta.jws-api', version: jakartaJwsVersion
	
	// Apache Commons Codec for Base64 encoding
	implementation group: 'commons-codec', name: 'commons-codec', version: commonsCodecVersion
	implementation group: 'org.apache.commons', name: 'commons-lang3', version: commonsLang3Version
    api group: 'org.apache.commons', name: 'commons-text', version: commonsTextVersion

	testImplementation group: 'junit', name: 'junit', version: junitVersion

	// Apache CXF tools for WSDL processing - updated to Jakarta EE compatible version
	ws group: 'org.apache.cxf', name: 'cxf-tools', version: cxfVersion
	ws group: 'org.apache.cxf', name: 'cxf-tools-wsdlto-databinding-jaxb', version: cxfVersion
	ws group: 'org.apache.cxf', name: 'cxf-tools-wsdlto-frontend-jaxws', version: cxfVersion
}

task wsdl2Java() {
	if (!wsdlDir.listFiles()) {
		// do nothing
	} else {
		inputs.files wsdlDir.listFiles()
		outputs.dir generatedWsdlDir
		doLast {
			// Ensure the generated directory exists
			generatedWsdlDir.mkdirs()
			
			wsdlsToGenerate.each { argsin ->
				argsin.add(argsin.size - 1, '-d')
				argsin.add(argsin.size - 1, 'src/generated/java')
				argsin.add(argsin.size - 1, '-wsdlLocation')
				argsin.add(argsin.size - 1, '/wsdl/MOA-SPSS-2.0.0.wsdl')
				javaexec {
					classpath configurations.ws
					mainClass = 'org.apache.cxf.tools.wsdlto.WSDLToJava'
					args = argsin
					systemProperties = ['exitOnFinish':'TRUE']
				}
			}
		}
	}
}

task releases(type: Copy) {
	from jar.outputs
	into rootDir.toString() + "/releases/" + version
}

releases.dependsOn jar
releases.dependsOn sourcesJar

test {
	systemProperties 'property': 'value'
}
