apply plugin: 'java-library'
apply plugin: 'eclipse'
apply plugin: 'application'

application {
    mainClass = "at.gv.egiz.pdfas.cli.Main"
}

repositories {
	mavenLocal()
    mavenCentral()
}

task releases(type: Copy) {
	from distZip.outputs
	from distTar.outputs
	into rootDir.toString() + "/releases/" + version
}

configurations { 
	pdfBox3Compile
}

sourceSets{
	pdfBox3{
		compileClasspath = configurations.pdfBox3Compile
		runtimeClasspath = configurations.pdfBox3Compile + main.runtimeClasspath
	}
}
			   
dependencies {
	implementation project (':pdf-as-lib')
	implementation project (':signature-standards:sigs-pkcs7detached')
	implementation project (':signature-standards:sigs-pades')
	implementation project (':pdf-as-moa')
    implementation project (':pdf-as-pdfbox-3')
    implementation group: 'org.apache.commons', name: 'commons-collections4', version: commonsCollectionsVersion
	implementation group: 'commons-cli', name: 'commons-cli', version: commonsCliVersion
	implementation group: 'jakarta.activation', name: 'jakarta.activation-api', version: jakartaActivationVersion
	implementation group: 'ch.qos.logback', name: 'logback-classic', version: logbackVersion
}


startScripts{
	classpath+=sourceSets.pdfBox3.compileClasspath
}

compileJava{
    classpath=sourceSets.main.compileClasspath
	classpath+=sourceSets.pdfBox3.compileClasspath
}


releases.dependsOn jar
releases.dependsOn sourcesJar
releases.dependsOn distZip
releases.dependsOn distTar

distZip.dependsOn startScripts


test {
    systemProperties 'property': 'value'
}
