name: check-dependencies.yml
on:
  pull_request:

jobs:
  dependency-review:
    name: Dependency review
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Review dependency changes
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
