name: semgrep

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - development
  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:
    name: Semgrep CE
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run Semgrep
        run: semgrep scan --config auto --error --sarif --sarif-output semgrep.sarif .

      - name: Upload Semgrep SARIF artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif
          path: semgrep.sarif

      # enable this if we go public
      # - name: Upload to GitHub code scanning
      #   if: always()
      #   uses: github/codeql-action/upload-sarif@v4
      #   with:
      #     sarif_file: semgrep.sarif
      #     category: semgrep